### ISSUE TITLE
rename function to explicit their boolean output?

### ISSUE THREAD

**Issue by joelgombin** [InseeFrLab/validinsee#2]
Thanks for the package, very useful!
Would it make sense to rename the functions to things like `is_valid_siren`? I somehow feel that it would make more sense. What do you think?

**Comment by py-b** [comment]
Thank you Joël, that's a good point.

The idea behind the chosen names is that they are both in english in french (as the package will be used mainly by french speakers).
I'll probably stick with that idea.

Naming things is hard. 😅
